/**
 * Re-exports the compiled ShadowPass contract module for the browser.
 *
 * The module is generated by `compact compile` (root: `npm run compile`)
 * and copied here by `npm run copy-zk-assets`.
 */

export { Contract, ledger, pureCircuits } from '../compiled-contract.js';
